# Generated by Django 4.0.5 on 2022-06-04 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_accesstoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='forum_user_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID del foro'),
        ),
    ]
