# Generated by Django 4.0.5 on 2022-06-18 18:12

import apps.authentication.workflows
from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_forum_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesstoken',
            name='state',
            field=django_fsm.FSMIntegerField(choices=[(0, 'Cancelado'), (1, 'Enviado')], default=apps.authentication.workflows.UserTokenWorkflow.Choices['SEND'], protected=True, verbose_name='estado'),
        ),
    ]
