# Generated by Django 4.0.5 on 2022-06-18 18:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_accesstoken_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesstoken',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='fecha de creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accesstoken',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='última fecha de modificación'),
        ),
    ]
