# Generated by Django 4.0.5 on 2022-06-24 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_reserved_stock_product_stock_productrefill'),
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='purchaseline',
            unique_together={('product', 'purchase')},
        ),
    ]
